[programs.localnet]
instruments = "instruments11111111111111111111111111111111"
dex = "Dex1111111111111111111111111111111111111111"

[registry]
url = "https://trezoaanchor.projectserum.com"

[provider]
cluster = "localnet"
wallet = "~/.config/trezoa/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
